# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-02 14:25
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name'],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('hours', models.TimeField(blank=True, help_text=b'You can also enter minutes.')),
                ('message', models.CharField(help_text=b'Brief description of work done.<br>Add SVN revision or issue number if available.', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=b'Created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name=b'Updated at')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Employee')),
            ],
            options={
                'ordering': ['date'],
                'verbose_name_plural': 'entries',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Client')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Project'),
        ),
        migrations.AddField(
            model_name='entry',
            name='work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.WorkType'),
        ),
        migrations.AddField(
            model_name='employee',
            name='project',
            field=models.ManyToManyField(to='log.Project'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_type',
            field=models.ManyToManyField(to='log.WorkType'),
        ),
    ]
