# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-06 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_auto_20171204_1324'),
        ('log', '0003_setup_permissions'),
    ]

    operations = [
    ]
